# Site settings
title: "Juan Monsalve | Frontend Developer"
description: "Juan Monsalve Resume page."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Juan Monsalve"
resume_title:                   "Frontend Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "juanchomonsalve92@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+57 3183776216"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Highly skilled and experienced Software Developer adept in all stages of web development with 8 years in the industry, having developed and delivered numerous web projects using the latest technologies and methodologies. Proficient in HTML, CSS, JavaScript and React. Fast learner, able to effectively self-manage, as well as collaborate in a team setting, providing ideas to improve processes and results. With a passion for coding and a strong attention to detail, consistently delivering high-quality, innovative and effective solutions.</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/juanmonsalv3"
  # resume_twitter_url:           "http://twitter.com/juanchomogi"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/monsalvejuan"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://juanmonsalve.dev"
  # resume_medium_url:            "Insert link"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
